### ISSUE TITLE
Quotes for parts of idioms

### ISSUE THREAD

**Issue by svenha** [rafehr/vid-disambiguation-sharedtask#2]
I saw in SE5BG.1411 that part of the idiom is quoted. As these double quotes are optional and too easy indicators for the class `figuratively`, I suggest to remove such quotes.

**Comment by rafehr** [comment]
We discussed this issue and decided to not remove these kind of quotes, because we do not want to make the task artificially harder. It could be that these kind of makers were used by annotators to determine the reading of an expression. One could even imagine instances, where quotes are the only way to determine the correct reading of an expression:

Sie ging in die Küche und schon roch sie den "Braten".

vs.

Sie ging in die Küche und schon roch sie den Braten.

Removing the quotes in this case would mean we'd loose a very strong indicator for a figurative meaning. So it would be kind of unfair to the systems if they had to work without this information.

But do not worry - there will be enough challenges in the dataset ;-)
