### ISSUE TITLE
Ungrammatical sentences containing idioms

### ISSUE THREAD

**Issue by svenha** [rafehr/vid-disambiguation-sharedtask#3]
The data contains ungrammatical sentences, e.g. SE5BG.81 (`aus` instead of `auf`). I see 3 options: 1. leave it as is, 2. correct it (to have clean data without other problems), 3. exclude (or annotate). Our approach will include a parser (without error corrections or similar), so option 1 is not our favorite :-)

BTW: Thanks for setting up this interesting task!

**Comment by rafehr** [comment]
Thanks for bringing this to our attention! But I fear we have to dissapoint you, because we will settle for option 1. A part of the corpus was retrieved using a web crawler, so it also contains data from internet forums, etc. Since such data is naturally messy, one could argue that correcting the grammar in such cases would distort the dataset. But the majority of the data (nearly 7000 sentences) stems from newspaper articles which should contain very little ungrammatical sentences.

We wish you good luck for the competition!
